const tool = [
  {
    id: 1,
    img: 'https://image.shutterstock.com/image-photo/coxs-bazar-chittagong-bangladesh-6172017-260nw-1189314049.jpg',
    name: 'Cox-Bazar',
    area: '23.4 km²',
    cost: 7.5,
    country: 'Bangladesh',
    division: 'Chittagong Division',
  },
  {
    id: 2,
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Sundarban_Tiger.jpg/1200px-Sundarban_Tiger.jpg',
    name: 'Sundarbans',
    area: '10000 km²',
    cost: 6,
    country: 'Bangladesh',
    division: 'Khulna Division',
  },
  {
    id: 3,
    img: 'https://www.travelmate.com.bd/wp-content/uploads/2018/07/Main.jpg',
    name: 'Kuakata',
    area: '1.8 km²',
    cost: 5.5,
    country: 'Bangladesh',
    division: 'Barisal Division',
  },
  {
    id: 4,
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Zero_Point_at_Zuflong.jpg',
    name: 'Jaflong',
    area: '12.5 km²',
    cost: 12.5,
    country: 'Bangladesh',
    division: 'Sylhet Division',
  },
  {
    id: 5,
    img: 'https://alltourinfo.com/wp-content/uploads/2021/03/Sajek-Valley-Bangladesh-1280x720.jpg',
    name: 'Sajek',
    area: '6.1 km²',
    cost: 14,
    country: 'Bangladesh',
    division: 'Chittagong Division',
  },
  {
    id: 6,
    img: 'https://image.shutterstock.com/image-photo/beautiful-view-dirt-road-tea-260nw-1975476134.jpg',
    name: 'Sreemangal',
    area: '450.7 km²',
    cost: 9.3,
    country: 'Bangladesh',
    division: 'Sylhet Division',
  },
  {
    id: 7,
    img: 'https://i0.wp.com/pasadai.com/wp-content/uploads/2019/07/Darjeeling-District.jpg?fit=750%2C420&ssl=1',
    name: 'Darjeeling',
    area: '2092 km²',
    cost: 34,
    country: 'India',
    division: 'Jalpaiguri Division',
  },
  {
    id: 8,
    img: 'https://alchetron.com/cdn/mahasthangarh-8bbb3b16-a117-442f-930a-af7d81d998c-resize-750.jpeg',
    name: 'Mohasthan Garh',
    area: '2 km²',
    cost: 11.6,
    country: 'Bangladesh',
    division: 'Rajshahi Division',
  },
  {
    id: 9,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa1DwecpNMmtALAalqaBCS_NX5d0fVgW1D4g&usqp=CAU',
    name: 'Sonargaon',
    area: '0.73 km²',
    cost: 7,
    country: 'Bangladesh',
    division: 'Dhaka Division',
  },
  {
    id: 10,
    img: 'https://media-cdn.tripadvisor.com/media/photo-s/0f/40/a9/8d/park-map.jpg',
    name: 'Safari Park',
    area: '15.14 km²',
    cost: 2.4,
    country: 'Bangladesh',
    division: 'Dhaka Division',
  },
  {
    id: 11,
    img: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/2b/4d/d1/visit-coral-island-saint.jpg',
    name: "St. Martin's Island",
    area: '3 km²',
    cost: 22.5,
    country: 'Bangladesh',
    division: 'Chittagong Division',
  },
  {
    id: 12,
    img: 'https://bangladeshpost.net/webroot/uploads/featureimage/2019-10/5da330de4c3ee.jpg',
    name: 'Kaptai Lake',
    area: '688 km²',
    cost: 10,
    country: 'Bangladesh',
    division: 'Chittagong Division',
  }
]